version: "3.8"

services:
  ips:
    # platform: amd64
    # network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /ips/
    restart: always
    command: ["dumb-init", "-cv", "--", "bash", "-c", "yarn run start:local"]
    container_name: ips
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - NODE_ENV=local
    networks:
      - My_net
    ports:
      - "3012:3012"
    volumes:
      - ./:/ips/
      - node_modules:/ips/node_modules
     
  #############################################################################################################################################################################
  
volumes:
  node_modules: {}
networks:
  My_net:
    driver: bridge
